# Generated by Django 3.2 on 2021-04-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AlterField(
            model_name='book',
            name='categoria2',
            field=models.ManyToManyField(to='biblio.Category'),
        ),
    ]
