# Generated by Django 3.2 on 2021-04-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_auto_20210428_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categoria2',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to=''),
        ),
    ]
