# Generated by Django 3.2 on 2021-04-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_auto_20210428_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
